### ISSUE TITLE
Where does `banned_at` get set?

### ISSUE THREAD

**Issue by JTallis** [cybercog/laravel-ban#11]
I've looked around and I cannot seem to find where `banned_at` ever gets set or unset. Expired bans do not set it to null (as it's simply a deletion on the ban record) and creation of bans don't seem to set it either.

I'm a little confused. Am I missing something?

**Comment by JTallis** [comment]
Nevermind, it's handled in the observers. Never used them before!

**Comment by a-komarev** [comment]
@JTallis yes, you are right. They are handled by the `BanObserver`. If you need this package to work without observer you could extend ServiceProvider and omit `bootObservers` method call.
