### ISSUE TITLE
Not working with Laravel 5.5

### ISSUE THREAD

**Issue by sam-cogan** [cybercog/laravel-ban#14]
Trying to add to Laravel 5.5 results in the following composer error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laravel/framework (locked at v5.4.32, required as 5.5.*) is satisfiable by laravel/framework[v5.4.32] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package phpunit/phpunit (locked at 5.7.21, required as ~6.0) is satisfiable by phpunit/phpunit[5.7.21] but these conflict with your requirements or minimum-stability.
  Problem 3
    - backpack/base 0.7.21 requires laravel/framework 5.3.*|5.4.* -> satisfiable by laravel/framework[5.3.x-dev, 5.4.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9, v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.14, v5.4.15, v5.4.16, v5.4.17, v5.4.18, v5.4.19, v5.4.2, v5.4.20, v5.4.21, v5.4.22, v5.4.23, v5.4.24, v5.4.25, v5.4.26, v5.4.27, v5.4.28, v5.4.29, v5.4.3, v5.4.30, v5.4.31, v5.4.32, v5.4.33, v5.4.34, v5.4.35, v5.4.36, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9] but these conflict with your requirements or minimum-stability.
    - backpack/base 0.7.21 requires laravel/framework 5.3.*|5.4.* -> satisfiable by laravel/framework[5.3.x-dev, 5.4.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9, v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.14, v5.4.15, v5.4.16, v5.4.17, v5.4.18, v5.4.19, v5.4.2, v5.4.20, v5.4.21, v5.4.22, v5.4.23, v5.4.24, v5.4.25, v5.4.26, v5.4.27, v5.4.28, v5.4.29, v5.4.3, v5.4.30, v5.4.31, v5.4.32, v5.4.33, v5.4.34, v5.4.35, v5.4.36, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9] but these conflict with your requirements or minimum-stability.
    - backpack/base 0.7.21 requires laravel/framework 5.3.*|5.4.* -> satisfiable by laravel/framework[5.3.x-dev, 5.4.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9, v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.14, v5.4.15, v5.4.16, v5.4.17, v5.4.18, v5.4.19, v5.4.2, v5.4.20, v5.4.21, v5.4.22, v5.4.23, v5.4.24, v5.4.25, v5.4.26, v5.4.27, v5.4.28, v5.4.29, v5.4.3, v5.4.30, v5.4.31, v5.4.32, v5.4.33, v5.4.34, v5.4.35, v5.4.36, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9] but these conflict with your requirements or minimum-stability.
    - Installation request for backpack/base (locked at 0.7.21, required as ^0.7.16) -> satisfiable by backpack/base[0.7.21].

**Comment by a-komarev** [comment]
Hello @sam-cogan! Thanks for notice this. I suppose issue was raised because of PHPUnit 6.0 was defined only on master branch. I've released v3.0.1 which should fix this.

**Comment by a-komarev** [comment]
@sam-cogan does this helps?

**Comment by sam-cogan** [comment]
Yep, that sorted it, thanks!

**Comment by a-komarev** [comment]
Thank you for the confirmation!

**Comment by jadamec** [comment]
I've same problem with upgrading Laravel to 6.x vers. Thanks!

**Comment by antonkomarev** [comment]
@jadamec create new issue and write there what package version is defined in composer.json and provide console output if possible. Thanks.

**Comment by jadamec** [comment]
> @jadamec create new issue and write there what package version is defined in composer.json and provide console output if possible. Thanks.

Already fixed. I just need to update this package first and then Laravel... :) Thanks anyway.
