### ISSUE TITLE
shouldApplyBannedAtScope() causes unban() to be unusable.

### ISSUE THREAD

**Issue by rickmacgillis** [cybercog/laravel-ban#28]
I tried to apply the `shouldApplyBannedAtScope()` method on the `User` model, and when I called `$user->unban()` in my unit test, it started complaining about the `bans` property being called on `NULL` in `BanObserver`. That's because the `morphTo` wasn't able to locate the now-deleted model through the `bannable` property.

**Comment by antonkomarev** [comment]
@rickmacgillis I'll check it ASAP, could you provide a code sample how to achieve this bug?

**Comment by rickmacgillis** [comment]
Steps to reproduce:

1. Add the `shouldApplyBannedAtScope()` method to the bannable such that it returns `true` always.
2. Create a user to ban.
3. Ban the user.
4. Try to unban the user.

**Comment by antonkomarev** [comment]
@rickmacgillis confirmed and fixed in PR #30. Will be included in next release.
