### ISSUE TITLE
Getting a way to know who banned

### ISSUE THREAD

**Issue by Epistol** [cybercog/laravel-ban#36]
Hello there, I see that the table "bans" store the ban user ID and type of "banner" (if user or else) which led me to think there was a simple way to get the user id of the administrator or entity who banned the user, but sadly, there is none ... is it planned ?

Or shall we make a PR ? 

Thank you for this great repo,
Epistol

**Comment by antonkomarev** [comment]
If there are issues with it - feel free to continue conversation here.
