### ISSUE TITLE
support to ban by visiter not users

### ISSUE THREAD

**Issue by badrshs** [cybercog/laravel-ban#42]
Hi, Does this package support ban visiter ??? no user here , I want to ban the visiter  based on his ip address.
So I will have additional table related to the ip address im going to block

thank you for helping :)

**Comment by antonkomarev** [comment]
Hi @badrshs! This question was raised before: #20 
Since Bannable model is polymorphic - IP address model could be banned. Just write your middleware to check for it.

**Comment by badrshs** [comment]
haaa , good idea , I didnt think about that 😁😁 

thanks
