### ISSUE TITLE
Is delete ban necessary

### ISSUE THREAD

**Issue by reigningkingforever** [cybercog/laravel-ban#51]
Is it necessary to delete ban?
Why not just check if the expired_at time is > than now( ). 
If yes, allow user
If no, don't allow user?
I'm thinking of editing your code to behave like this in my project so that I don't need to set cron job. What do you advise ? How can I do this in your code.

**Comment by antonkomarev** [comment]
@reigningkingforever If you don't want to use CRON job - then you could create a middleware and check if user ban is expired on login and delete this ban before the login.

**Comment by reigningkingforever** [comment]
Nooo.. you didn't get my question.
What i'm asking is, If I don't delete the ban, is there any problem ?

**Comment by antonkomarev** [comment]
User will be banned then and will be unable to access endpoints which uses forbid banned users middleware.
