### ISSUE TITLE
Support for user UUIDs

### ISSUE THREAD

**Issue by johlton** [cybercog/laravel-ban#52]
I'd like to see this working for user UUIDs out of the box. For now, I help myself with 2 subsequent migrations which alter the columns `bannable_id` and `created_by_id` to `string(36)`. This works so far but I am not sure about any side effects. It would be great if there would be a config option for this.

**Comment by antonkomarev** [comment]
Hi @johlton! Thank you for the feedback.

There is no plan to make `bannable_id` & `created_by_id` column types configurable. Motivation not obvious on the first sight, but pretty simple in fact. Imagine the situation when you have 2 Bannable models:
- `User` model has BIGINT id key
- `Bot` model has UUID id key

There is no way to store both of this models IDs in `bannable_id` column without enormous database queries performance issues.

As a solution I'd prefer to refactor this package to new architecture similar to the [Laravel Love package](https://github.com/cybercog/laravel-love). Then package wouldn't know anything about bannable models structure and will be able to work with any column type.

I noticed that you've using `string(36)` for UUID columns. This might lead you to performance issues on big databases. There is Laravel `$table->uuid('id_column')` helper method which should work better.

**Comment by johlton** [comment]
Hi Anton, thanks for your quick reply. 

> I noticed that you've using `string(36)` for UUID columns. This might lead you to performance issues on big databases. There is Laravel `$table->uuid('id_column')` helper method which should work in more optimized way.

I tried to do it with type `uuid` but then Doctrine DBAL threw an Exception:

> Doctrine\DBAL\DBALException  : Unknown column type "uuid" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

So I figured the string type.

**Comment by antonkomarev** [comment]
If UUID is not working for you - you'd better use `CHAR(36)` instead of `VARCHAR`. UUID has fixed length and your ids will consume more database storage if they will be stored as variable-length strings. Here is a [MySQL reference about CHAR column type](https://dev.mysql.com/doc/refman/5.7/en/char.html).

**Comment by johlton** [comment]
Totally agree with you here, but it throws the same DBAL exception which does Not recognize the char type.

**Comment by johlton** [comment]
I could use a `DB::table` construct here, or dropping and re-adding the columns. Thanks for your input!

**Comment by antonkomarev** [comment]
If you have time - I advise you to look for a solution in StackOverflow or ask in Laravel discord or Slack chats how to deal with this exception. I'm sure it could be fixed very easy, but don't clearly remember how.
Using `DB::table` is not that bad, but it's hardcode and if you will decide to switch database, for example on PostgreSQL later - then you have to rewrite your migrations.

**Comment by johlton** [comment]
It works now. After fetching [ramsey/uuid-doctrine](https://github.com/ramsey/uuid-doctrine) via `composer require ramsey/uuid-doctrine --dev`, add the following:

**app/Providers/AppServiceProvider.php**
```
try {
    \Doctrine\DBAL\Types\Type::addType('uuid', 'Ramsey\Uuid\Doctrine\UuidType');
} catch (DBALException $e) {
    Log::error($e->getMessage());
}
```

Now it's possible to use a migration like this:
```
Schema::table('bans', function (Blueprint $table) {
    $table->uuid('bannable_id')->change();
    $table->uuid('created_by_id')->change();
});
```
Thanks again, Anton, and keep up the good work!

**Comment by antonkomarev** [comment]
Thanks for sharing the solution! It might be useful for others too.
