### ISSUE TITLE
Laravel 7 compatibility

### ISSUE THREAD

**Issue by vesper8** [cybercog/laravel-ban#56]
`4.2` is not compatible with Laravel 7 due to `illuminate/events 5.5.*|5.6.*|5.7.*|5.8.*|^6.0`

@antonkomarev Could you please release a new version with Laravel 7 compatibility?

Thanks a lot!

**Comment by antonkomarev** [comment]
Hey @vesper8! Yes, I'm gonna upgrade all my packages this weekend.
I'm always open to pull requests if you want to get this updates faster.

**Comment by antonkomarev** [comment]
Laravel 7.x support was added in Laravel Ban v4.2.1

**Comment by vesper8** [comment]
thanks for the quick turnaround!
