### ISSUE TITLE
how can I ban only once?

### ISSUE THREAD

**Issue by joantp** [cybercog/laravel-ban#57]
Is there a way to ban only if model is not already banned? So that I'd have just 0 or 1 ban record per user. 
What method should I overwrite?

Thank you!

**Comment by antonkomarev** [comment]
The easiest way - make a check in your controller if your user is already banned:

```php
if ($user->isBanned()) {
    abort(409);
}

$user->ban();
```

**Comment by joantp** [comment]
Ok. This is what I actually do. Thank you for your fast answer.
