### ISSUE TITLE
$user->isNotBanned not working in a blade file

### ISSUE THREAD

**Issue by Maxillarious** [cybercog/laravel-ban#58]
I did everything just as the instruction, everything seems to be working fine.

But, there is an issue,

When i use `@if($post->user->isNotBanned() == true)` in blade file,
i get this error: `Call to a member function isNotBanned() on null`

**EDIT**
i have this in my blade file:
```
@if($posts->count() != 0)

    @foreach($posts as $post)
     
     <!-- If this post's user is not banned display his post -->
    @if($post->user->isNotBanned() == true)
     Show Bookmarked post
    @endif

    @endforeach

@endif
```

Thank you

**Comment by antonkomarev** [comment]
@Maxillarious that issue not related to package, it means that `$post->user` returns null value.
