### ISSUE TITLE
Laravel 8 unsupport and bug

### ISSUE THREAD

**Issue by jud3v** [cybercog/laravel-ban#62]
### Details

- Laravel version: 8.1.0
- cyborg version 4.2.x
- mysql version: 
    Production: Ver 15.1 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
    Local (dev): Ver 15.1 Distrib 10.4.14-MariaDB, for Linux (x86_64) using  EditLine wrapper

### Description

Hello i have don't heck if your package is ready for laravel 8 so is my fault if is this case.

My problem is if i run this command: `ban:delete-expired` every day at 7:00 in UTC timezone i will got these bug:

- Some of my model of `Advertise.php`,`Category.php`,'Topic.php`,`ProductCategory.php` will be deleted, and if one user or multiples users is banned, in the next schedule your command will ban every users, i have softDelete so i can recover everythings for that is really good 😄 

### Step to reproduce:

- install of cyborg in laravel version 7.25.x : all work like schedule, ban, ...
- upgrade laravel version 8.1.0 from 7.25.x because laravel telescope have bug in version 7.25.x by following docs
- install of ` composer require laravel/legacy-factory` support legacy models and factories
- adding command for check and unban users from your package in `app\Console\Kernel.php`.
- wait schedule.
- some models will be deleted

### Answer

Did your package support laravel 8 ?
Your package can access to relation from any models ? ( that really not good because some model can be delete with onDeleteCascade() )

**Comment by antonkomarev** [comment]
Could you create test project which reproduces this bug? Then I will be available to dive in quicker.

**Comment by jud3v** [comment]
Nope but i have follow the tutorial in the readme.md i will try it tomorrow.

**Comment by jud3v** [comment]
So it's me i have this on my route: `Route::middleware('pgp')->middleware('banned')` that don't work in laravel and an user has access to my backend and them have delete some of my data so... That not a support or anything, your package support laravel 8 if user upgrade from 7 i think need to test directly on laravel 8, thank you Bye 😄.

**Comment by olkotz** [comment]
i have the same problem in Laravel 8. Dosen't work... and dosent unban he user to... not work in laravel 8.
