### ISSUE TITLE
Inertia compatibility

### ISSUE THREAD

**Issue by Im-Fran** [cybercog/laravel-ban#68]
I'm using the middleware 'forbid-banned-user', which is working as expected but inertiajs has a little problem with redirects, you must specify the redirect response code 303 which is explained [here](https://inertiajs.com/redirects#303-response-code), it would be useful to have like a setting that enables/disables the inertia fix, like:
```php
// ...
'inertia-fix' => false, // default false, you can change it to true.
// ...
```
and if it's true you will add 303 as redirect response code. I would do it by myself but I'm a bit busy.

**Comment by antonkomarev** [comment]
Middleware my be on your side, just copy-paste it to your app

**Comment by Im-Fran** [comment]
I already did, just for future users with the same issue it would be great to see :)

**Comment by antonkomarev** [comment]
Thank you for the contribution @Im-Fran! [Laravel Ban v4.6.0](https://github.com/cybercog/laravel-ban/releases/tag/4.6.0) has been released with Inertia support. You are in [contributors list](https://github.com/cybercog/laravel-ban#contributors) now 🎉

**Comment by Im-Fran** [comment]
Awesome! Thanks for the awesome package!
